# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pan and Pop' do
	pod 'pop', :git => 'https://github.com/facebook/pop.git'
end

